Декоративные элементы на главной странице
htmlacademy-htmlcss/171670-sedona-30 pull request #10
Opened 2021-02-17 18:22 UTC by timeria

2021-02-17 19:20 UTC, raccoonroman requested changes
* вот что при фокусе на кнопку получается https://prnt.sc/zvyndx
* при фокусе содержимое инпута не должно смещаться https://prnt.sc/zvyq1t
* должна быть тень по бокам https://prnt.sc/zvyu44

2021-02-17 19:20 UTC, raccoonroman commented on css/style.css
> +  top: 86px;
```suggestion
  top: 100%;
```

2021-02-17 19:20 UTC, raccoonroman commented on css/style.css
> +.form-input input:hover + svg path {
https://up.htmlacademy.ru/htmlcss/30/project/sedona#sedona-3-12 кнопка календаря не должна зависеть от состояния инпута.

2021-02-17 19:20 UTC, raccoonroman commented on css/style.css
> +.form-item input::-moz-placeholder {
префиксы руками лучше не ставить, для этого есть автопрефиксер https://autoprefixer.github.io

2021-02-17 19:20 UTC, raccoonroman commented on css/style.css
> +  color: var(--basic-black);
обычно цвет плейсхолдера от текста инпута отличается только цветом. А остальные свойства для плейсхолдера привносят только лишние проблемы. Посмотри, какая у тебя стилизация текста https://prnt.sc/zvxmlo

2021-02-17 19:20 UTC, raccoonroman commented on css/style.css
> +.form-item .form-number input {
https://up.htmlacademy.ru/htmlcss/30/criteries#d7

2021-02-17 19:20 UTC, raccoonroman commented on css/style.css
> +  min-width: initial;
```suggestion
  min-width: 0;
```

2021-02-17 19:20 UTC, raccoonroman commented on index.html
> +          <form action="">
```suggestion
          <form action="https://echo.htmlacademy.ru/" target="_blank">
```

2021-02-17 19:20 UTC, raccoonroman commented on index.html
> +              <svg width="21" height="23" viewBox="0 0 21 23" fill="none" xmlns="http://www.w3.org/2000/svg" class="form-input-calendar">
это должна быть кнопка https://up.htmlacademy.ru/htmlcss/30/project/sedona#sedona-3-12

2021-02-17 19:20 UTC, raccoonroman commented on index.html
> +              <svg width="21" height="23" viewBox="0 0 21 23" fill="none" xmlns="http://www.w3.org/2000/svg" class="form-input-calendar">
саму заливку проще и лучше задавать самому тегу svg, чем отдельным частям (path, rect, и т. д.) если вся иконка одинакового цвета

2021-02-17 19:20 UTC, raccoonroman commented on index.html
> +                  <svg width="12" height="3" viewBox="0 0 12 3" fill="none" xmlns="http://www.w3.org/2000/svg">
```suggestion
                  <svg width="12" height="3" viewBox="0 0 12 3" fill="#A9A9A9">
```

2021-02-17 19:20 UTC, raccoonroman commented on index.html
> +                  <rect width="12" height="3" fill="#A9A9A9"/>
```suggestion
                  <rect width="12" height="3"/>
```

2021-02-17 19:20 UTC, raccoonroman commented on index.html
> +                <button class="form-number-item munus">
Сейчас при клике на кнопки "+" и "-" у меня отправляется форма. Угадай почему.

2021-02-17 19:20 UTC, raccoonroman commented on index.html
> +            <input type="submit" value="Найти" class="form-button">
Это устаревший способ. Делай всегда кнопкой. 
```suggestion
            <button class="form-button">Найти</button>
```

2021-02-17 19:20 UTC, raccoonroman commented on index.html
> +            </div>
соблюдай вложенность. Должна быть древовидная структура

2021-02-19 18:24 UTC, timeria commented on css/style.css
> +.form-item input::-moz-placeholder {
Не смогла через него на placeholder постаивть

2021-02-19 21:25 UTC, raccoonroman approved these changes

2021-02-19 21:25 UTC, raccoonroman commented on index.html
> +            <img src="img/banner-right.jpg" alt="Настоящий городок" class="features-img features-img-right">
https://up.htmlacademy.ru/htmlcss/30/criteries#d1

2021-02-19 21:25 UTC, raccoonroman commented on index.html
> +          <img src="img/banner-left.jpg" alt="Там есть Мост дьявола" class="features-img features-img-left">
https://up.htmlacademy.ru/htmlcss/30/criteries#d1

2021-02-19 21:25 UTC, merged