Внутренняя страница декорирование
htmlacademy-htmlcss/171670-sedona-30 pull request #11
Opened 2021-02-21 17:04 UTC by timeria

2021-02-21 19:22 UTC, raccoonroman requested changes
* У выбраного чекбокса здесь должны быть пробелы https://prnt.sc/1031hyi
* При наведении центр курсора не должен смещаться https://prnt.sc/1031iuu
* текст "от" и "до" должен оставаться при введенных значениях https://prnt.sc/1031jnq
* https://up.htmlacademy.ru/htmlcss/30/criteries#d10 нужно прописывать фоновый цвет https://prnt.sc/1031l6u, и на главной тоже

2021-02-21 19:22 UTC, raccoonroman commented on catalog.html
> +              <svg width="19" height="17" viewBox="0 0 19 17" fill="none">
изображения декоративные - должны выводиться с помощью стилей. А так это лишние теги

2021-02-21 19:22 UTC, raccoonroman commented on css/style.css
> +  visibility: hidden;
https://up.htmlacademy.ru/htmlcss/30/criteries#d26
фокусом с клавиатуры должна быть возможность снять или поставить галочку чекбокса. Для этого понадобится класс .visually-hidden

2021-02-21 19:22 UTC, raccoonroman commented on css/style.css
> +.filter-name:before {
```suggestion
.filter-name::before {
```

2021-02-21 19:22 UTC, raccoonroman commented on css/style.css
> +.filter-name:after {
```suggestion
.filter-name::after {
```

2021-02-21 19:22 UTC, raccoonroman commented on css/style.css
> +.filter-item input:checked + .filter-name:after {
```suggestion
.filter-item input:checked + .filter-name::after {
```

2021-02-21 19:22 UTC, raccoonroman commented on css/style.css
> +.price-controls:before {
```suggestion
.price-controls::before {
```

2021-02-21 19:22 UTC, raccoonroman commented on css/style.css
> +.price-controls:before {
https://stackoverflow.com/questions/32039959/what-the-difference-between-two-double-point-and-one-in-pseudo-selector

2021-02-21 19:22 UTC, raccoonroman commented on css/style.css
> +.price-controls input::-ms-input-placeholder {
https://up.htmlacademy.ru/htmlcss/30/criteries#d9

2021-02-21 19:22 UTC, raccoonroman commented on css/style.css
> +.price-controls input::-ms-input-placeholder {
нужен еще вариант без префикса

2021-02-22 21:02 UTC, raccoonroman requested changes

2021-02-22 21:02 UTC, raccoonroman commented on css/style.css
> +  background: url(../img/star-4.svg) no-repeat top right;
а если рейтинг будет из десяти звездочек? 10 разных картинок подгружать? Можно просто использовать одну иконку звездочки и свойство background-repeat. Дам маленькую подсказку https://codepen.io/chriscoyier/pen/vxgyRj

2021-02-22 21:50 UTC, timeria commented on css/style.css
> +  box-sizing: content-box;
У меня прописано для всех элементов, но с ним не работает верстка этих кнопок, вместо этого http://prntscr.com/1047bwl , получается так http://prntscr.com/1047d3i

2021-02-23 17:25 UTC, raccoonroman commented on css/style.css
> +  box-sizing: content-box;
потому что там значения прописаны под content-box. Их нужно переписать под  border-box

2021-02-23 17:31 UTC, raccoonroman approved these changes

2021-02-23 17:31 UTC, merged