Завершение верстки
htmlacademy-htmlcss/171670-sedona-30 pull request #12
Opened 2021-02-23 19:22 UTC by timeria

2021-02-23 19:43 UTC, raccoonroman requested changes

2021-02-23 19:43 UTC, raccoonroman commented on css/style.css
> +  line-height: 100%;
как вариант:
```suggestion
  line-height: 1;
```

2021-02-23 19:43 UTC, raccoonroman commented on css/style.css
> +  word-break: break-all;
не могу понять зачем в проекте word-break: break-all; вроде нет таких длинных слов, чтобы их переносить

2021-02-23 19:43 UTC, raccoonroman commented on css/style.css
> +input[type=number] {
https://up.htmlacademy.ru/htmlcss/30/criteries#d25

2021-02-23 19:43 UTC, raccoonroman commented on css/style.css
> +input::-webkit-inner-spin-button {
https://up.htmlacademy.ru/htmlcss/30/criteries#d25

2021-02-23 19:43 UTC, raccoonroman commented on catalog.html
> +  <link rel="stylesheet" href="css/style.min.css">
советую подключать минифицированый файл только в самом конце перед сдачей на предзащиту. Стили же еще будут меняться/добавляться

2021-02-23 19:43 UTC, raccoonroman commented on index.html
> +              <img src="img/banner-right.jpg" alt="Настоящий городок" class="features-img features-img-right">
https://up.htmlacademy.ru/htmlcss/30/criteries#d1

2021-02-24 17:14 UTC, timeria commented on css/style.css
> +  word-break: break-all;
В требованиях написано, что должно хорошо смотреться при добавлении любого контента. Я попробовала разные варианты, если не переносится, начинает наезжать на другие элементы. Или это ненужно?

2021-02-24 21:07 UTC, raccoonroman commented on css/style.css
> +  word-break: break-all;
верстка должна проходить тест на переполнение контентом. Но тестировать нужно адекватно)

2021-02-24 21:11 UTC, raccoonroman approved these changes
Гуд

2021-02-24 21:11 UTC, raccoonroman commented on css/style.css
> +.page-body .price-controls input::-moz-placeholder {
https://up.htmlacademy.ru/htmlcss/30/criteries#d7

2021-02-24 21:11 UTC, raccoonroman commented on css/style.css
> +  word-break: break-all;
верстка должна проходить тест на переполнение контентом. Но тестировать нужно адекватно)

2021-02-24 21:12 UTC, merged