Разметка главной страницы
htmlacademy-htmlcss/171670-sedona-30 pull request #2
Opened 2021-01-25 18:53 UTC by timeria

2021-01-25 20:52 UTC, raccoonroman requested changes

2021-01-25 20:52 UTC, raccoonroman commented on index.html
> +            <a href="">Гостиницы</a>
здесь будет ссылка на страницу каталога

2021-01-25 20:52 UTC, raccoonroman commented on index.html
> +        <h1>Седона — небольшой городок в Аризоне, заслуживающий большего! </h1>
странные символы, которые приходять из фигмы, нужно убирать:
https://prnt.sc/xmcdrd

2021-01-25 20:52 UTC, raccoonroman commented on index.html
> +      <section class="banner__small">
https://prnt.sc/xmce5y это все одна большая секция

2021-01-25 20:52 UTC, raccoonroman commented on index.html
> +          <div>— №1 —</div>
так как внутри текст, то здесь больше подойдет тег `p`

2021-01-25 20:52 UTC, raccoonroman commented on index.html
> +          <div>Седона - не аттракцион для туристов, там<br> течёт своя жизнь</div>
это абзац

2021-01-25 20:52 UTC, raccoonroman commented on index.html
> +      <section>
https://prnt.sc/xmch87 это должен быть список из пяти элементов, где первый элемент имеет еще внутренний подсписок

2021-01-25 20:52 UTC, raccoonroman commented on index.html
> +            <img src="" alt="Жильё">
декоративные иконки должны выводиться с помощью стилей а не разметки https://htmlacademy.ru/blog/education/all/content-or-decor-img

2021-01-25 20:52 UTC, raccoonroman commented on index.html
> +            <div>Рекомендуем пожить в настоящем<br> мотеле, всё как в кино!</div>
это абзац

2021-01-25 20:52 UTC, raccoonroman commented on index.html
> +            <div>Рекомендуем пожить в настоящем<br> мотеле, всё как в кино!</div>
не всегда текст нужно переносить с помощью `<br>`. Блоку нужно будет задать внутренний отступ, который может перенести текст как по макету

2021-01-25 20:52 UTC, raccoonroman commented on index.html
> +       <section class="banner__small banner__small--right">
давай пока не будем использовать БЭМ-методологию, так как в данном случае она используется не правильно. Если вдруг очень хочется, напиши мне, обсудим.

2021-01-25 20:52 UTC, raccoonroman commented on index.html
> +            <div class="">  Укажите предполагаемые даты поездки, и мы покажем вам лучшие предложения гостиниц в седоне  </div>
это абзац

2021-01-25 20:52 UTC, raccoonroman commented on index.html
> +          <h3>ПОИСК ГОСТИНИЦЫ В СЕДОНЕ</h3>
это кнопка

2021-01-25 20:52 UTC, raccoonroman commented on index.html
> +          <form action="">
форму пока нужно убрать. Они будут рассматриваться в соответствующей лекции

2021-01-25 20:52 UTC, raccoonroman commented on index.html
> +      <a href="https://htmlacademy.ru/intensive/htmlcss" target="_blank">
лайк за `target="_blank"` 👍

2021-01-25 20:52 UTC, raccoonroman commented on index.html
> +            <img src="" alt="utube">
```suggestion
            <img src="" alt="youtube">
```

2021-01-27 18:03 UTC, timeria commented on index.html
>  <html lang="ru">
new

2021-01-28 21:15 UTC, raccoonroman requested changes
Поднажми еще немного. Осталось совсем чуть-чуть ;)

2021-01-28 21:15 UTC, raccoonroman commented on index.html
> +     <p>Репозиторий создан для обучения на профессиональном онлайн‑курсе «<a href="https://htmlacademy.ru/intensive/htmlcss">HTML и CSS, уровень 1</a>».</p>
это уже не понадобится. Нужно удалить.

2021-01-28 21:15 UTC, raccoonroman commented on index.html
> +        <li>
пять лишек должно быть. https://prnt.sc/xrvbt0 У первой просто есть еще внутренний список

2021-01-28 21:15 UTC, raccoonroman commented on index.html
> +              <span style="background-image: url();"></span>
заводить тег под декоративные иконки не нужно. Просто убери этот спан

2021-01-28 21:15 UTC, raccoonroman commented on index.html
> +      <button>ПОИСК ГОСТИНИЦЫ В СЕДОНЕ</button>
```suggestion
      <button type="button">ПОИСК ГОСТИНИЦЫ В СЕДОНЕ</button>
```

2021-01-31 11:11 UTC, raccoonroman approved these changes

2021-01-31 11:11 UTC, raccoonroman commented
Все замечательно! Жду разметки страницы каталога.

2021-01-31 11:11 UTC, merged