Стилизация главной страницы
htmlacademy-htmlcss/171670-sedona-30 pull request #5
Opened 2021-02-07 09:49 UTC by timeria

2021-02-07 13:38 UTC, raccoonroman requested changes
Для первого раза замечаний хватит. Верни страницу каталога назад, я посмотрю стили еще там, раз ты их уже написала.

2021-02-07 13:38 UTC, raccoonroman commented on index.html
> +    <a href="/" class='main-footer-link'>#visitSEDONA</a>
https://up.htmlacademy.ru/htmlcss/30/criteries#b15
Используй какой-то один тип кавычек во всем html-файле
```suggestion
    <a href="/" class="main-footer-link">#visitSEDONA</a>
```

2021-02-07 13:38 UTC, raccoonroman commented on index.html
> +    ТЕЛ: <a href="tel:+74956660166" class='main-footer-phone'>+7(495) 666-01-66</a>
```suggestion
    ТЕЛ: <a href="tel:+74956660166" class="main-footer-phone">+7(495) 666-01-66</a>
```

2021-02-07 13:38 UTC, raccoonroman commented on index.html
> +  <svg width="115" height="41" viewBox="0 0 115 41" fill="none" xmlns="http://www.w3.org/2000/svg">
лишний атрибут в разметке
```suggestion
  <svg width="115" height="41" viewBox="0 0 115 41" fill="none">
```

2021-02-07 13:38 UTC, raccoonroman commented on css/style.css
> +  src: url("../fonts/PTSans.woff2") format("woff2"),
https://up.htmlacademy.ru/htmlcss/30/criteries#b15 должен использоваться один тип кавычек во всем файле стилей.

2021-02-07 13:38 UTC, raccoonroman commented on css/style.css
> +  src: url("../fonts/PTSans.woff2") format("woff2"),
шрифтов в папке fonts не вижу.

2021-02-07 13:38 UTC, raccoonroman commented on css/style.css
> +  src: url("../fonts/PTSans.woff2") format("woff2"),
https://up.htmlacademy.ru/htmlcss/30/criteries#b14 в названиях файлов не должно быть заглавных букв

2021-02-07 13:38 UTC, raccoonroman commented on css/style.css
> +      url("../fonts/PTSans.woff") format("woff"),
```suggestion
      url("../fonts/PTSans.woff") format("woff");
```

2021-02-07 13:38 UTC, raccoonroman commented on css/style.css
> +      url("../fonts/PTSans-Bold.woff") format("woff"),
```suggestion
      url("../fonts/PTSans-Bold.woff") format("woff");
```

2021-02-07 13:38 UTC, raccoonroman commented on css/style.css
> +  --basic-black:#000000;
нужно выбрать один стиль: либо стоит пробел после двоеточия в свойстве селектора, либо нет. Так как это нарушение критерия https://up.htmlacademy.ru/htmlcss/30/criteries#b15. Я рекомендую всегда ставить пробел:

2021-02-07 13:38 UTC, raccoonroman commented on css/style.css
> +  --basic-black:#000000;
```suggestion
  font-style: normal;
}
/* Variables */
:root{
  --basic-black: #000000;
```

2021-02-07 13:38 UTC, raccoonroman commented on css/style.css
> +   --area-grey-line: #E5E5E5;;
```suggestion
   --area-grey-line: #E5E5E5;
```

2021-02-07 13:38 UTC, raccoonroman commented on css/style.css
> +  font-family: 'PT Sans' , Arial, sans-serif;
```suggestion
  font-family: 'PT Sans', Arial, sans-serif;
```

2021-02-07 13:38 UTC, raccoonroman commented on css/style.css
> +  max-width: 1200px;
как-то ограничивать body не рекомендуется. Это только сейчас в макете весь контент ограничен по ширине. А может быть ситуация, когда нужно будет создать модальное окно, у которого серый фон на всю ширину вьюпорта. Это обязательно нужно учитывать. Потому лучше всего ограничивать ширину содержимого с помощью контейнера (div.container), который лежит внутри боди, а уже внутри него - header, main, footer.

2021-02-07 13:38 UTC, raccoonroman commented on css/style.css
> +ul{
не должно быть глобальных стилей https://up.htmlacademy.ru/htmlcss/30/criteries#d25
Вместо этого используй селектор по классу:
```suggestion
.list-reset{
```

2021-02-07 13:38 UTC, raccoonroman commented on css/style.css
> +  max-width: 1056px;
по макету - максимальная ширина контейнера должна быть 1200px

2021-02-07 13:38 UTC, raccoonroman commented on css/style.css
> +.main-navigation-list a{
рекомендуется перед скобкой всегда добавлять пробел:
```suggestion
.main-navigation-list a {
```

2021-02-07 13:38 UTC, raccoonroman commented on css/style.css
> +.features-item:first-child .features-title, .features-item:nth-child(2) .features-title, .features-item:first-child .features-text, .features-item:nth-child(2) .features-text{
селекторы через запятую всегда разделяй переносом строки, так намного читабельней:
```suggestion
.features-item:first-child .features-title,
.features-item:nth-child(2) .features-title,
.features-item:first-child .features-text,
.features-item:nth-child(2) .features-text{
```

2021-02-07 13:38 UTC, raccoonroman commented on css/style.css
> +}
в данном случае для первых двух пунктов лучше в разметке задать доп. класс напр. `blue-bg` чем строить такие сложные конструкции. 
```suggestion
.features-desc.blue-bg{
  color: var(--basic-white);
  background-color: var(--area-blue);
}
```

2021-02-07 13:38 UTC, raccoonroman commented on css/style.css
> +    padding: 50px 95px 55px 95px;
```suggestion
    padding: 50px 95px;
```

2021-02-07 13:38 UTC, raccoonroman commented on css/style.css
> +    box-sizing: border-box;
пропиши box-sizing глобально один раз и все, на примере критерия https://up.htmlacademy.ru/htmlcss/30/criteries#d25

2021-02-07 13:38 UTC, raccoonroman commented on css/style.css
> +  padding: 50px 50px 55px 50px;
```suggestion
  padding: 50px 50px 55px;
```

2021-02-07 13:38 UTC, raccoonroman commented on css/style.css
> +  padding: 58px 0 24px 0;
```suggestion
  padding: 58px 0 24px;
```

2021-02-07 13:38 UTC, raccoonroman commented on css/style.css
> +}
всегда для свойств добавляй отступы, это тоже базовый критерий по единообразию https://up.htmlacademy.ru/htmlcss/30/criteries#b15:
```suggestion
.main-form-title{
  font-size: 30px;
  line-height: 24px;
  margin-bottom: 30px;
}
```

2021-02-07 13:38 UTC, raccoonroman commented on css/style.css
> +.main-footer-social li a{
https://up.htmlacademy.ru/htmlcss/30/criteries#d7

2021-02-07 13:38 UTC, raccoonroman commented on css/style.css
> +.main-footer-social li a:focus img{
https://up.htmlacademy.ru/htmlcss/30/criteries#d7

2021-02-07 13:38 UTC, raccoonroman commented on css/style.css
> +.main-footer-contact, .main-footer-contact a{
```suggestion
.main-footer-contact,
.main-footer-contact a{
```

2021-02-07 13:38 UTC, raccoonroman commented on css/style.css
> +fill: var(--area-blue);
сразу заливку на svg вешай а не на path. Так вложеность уменьшиться

2021-02-07 19:51 UTC, raccoonroman requested changes
Оставил часть замечаний по странице каталога. Но ревью полностю не закончил, так как не все предыдущие замечания были исправлены. Нужно исправить их а так же те, которые я оставляю сейчас ниже

2021-02-07 19:51 UTC, raccoonroman commented on catalog.html
> +      <a href="" class="main-header-logo">
здесь должна быть ссылка на главную

2021-02-07 19:51 UTC, raccoonroman commented on catalog.html
> +    <nav class="main-navigation container">
не исправлено. Я говорил header, main и footer положить в див с классом container либо page-wrapper (если container уже занят) и объяснил почему.

2021-02-07 19:51 UTC, raccoonroman commented on catalog.html
> +            <li class="sort-list-item">Сортировка:</li>
```suggestion
            <li class="sort-item">Сортировка:</li>
```

2021-02-07 19:51 UTC, raccoonroman commented on catalog.html
> +        <article class="sort-rezult-item">
article - самостоятельная и независимая часть документа, страницы, приложения или сайта. Поэтому класс для article и его элементов должен быть соответствующим (название никак не завязано на внешнее окружение). Хорошим названием будет:
 ```suggestion
         <article class="hotel-card">
```

2021-02-07 19:51 UTC, raccoonroman commented on catalog.html
> +            <div class="sort-rezult-left">
```suggestion
            <div class="hotel-card-wrapper">
```

2021-02-07 19:51 UTC, raccoonroman commented on catalog.html
> +              <h3 class="sort-rezult-title"><a href="#!">Amara Resort & Spa</a></h3>
```suggestion
              <h3 class="hotel-card-title"><a href="#!">Amara Resort & Spa</a></h3>
```

2021-02-07 19:51 UTC, raccoonroman commented on catalog.html
> +              <p class="sort-rezult-desc">Гостиница <span>от 4000 Р.</span></p>
```suggestion
              <p class="hotel-card-desc">Гостиница <span>от 4000 Р.</span></p>
```

2021-02-07 19:51 UTC, raccoonroman commented on catalog.html
> +              <div class="sort-rezult-button">
```suggestion
              <div class="hotel-card-buttons">
```

2021-02-07 19:51 UTC, raccoonroman commented on catalog.html
> +            <div class="sort-rezult-right">
```suggestion
            <div class="hotel-card-right">
```

2021-02-07 19:51 UTC, raccoonroman commented on catalog.html
> +              <p class="sort-rezult-popular">Рейтинг: 8,5</p>
```suggestion
              <p class="hotel-card-rating">Рейтинг: 8,5</p>
```

2021-02-07 19:51 UTC, raccoonroman commented on catalog.html
> +  <footer class="main-footer container">
не обязательно писать main. Можно проще
```suggestion
  <footer class="footer container">
```

2021-02-08 15:40 UTC, timeria commented on css/style.css
> +  src: url("../fonts/PTSans.woff2") format("woff2"),
> шрифтов в папке fonts не вижу.

Вот они в папке http://prntscr.com/yq5xrt

2021-02-08 19:50 UTC, raccoonroman requested changes
Осталось немного

2021-02-08 19:50 UTC, raccoonroman commented on index.html
> +        <a href="/" class="main-header-logo">
на главной странице href нужно убрать либо прописать рабочий адресс

2021-02-08 19:50 UTC, raccoonroman commented on css/style.css
> +  url("../fonts/ptsans.woff") format("woff");
шрифты не подключены https://prnt.sc/yqttj5

2021-02-08 19:50 UTC, raccoonroman commented on css/style.css
> +  url("../fonts/ptsans.woff") format("woff");
можно немного подформатировать:
```suggestion
  src: url("../fonts/ptsans.woff2") format("woff2"),
       url("../fonts/ptsans.woff") format("woff");
```

2021-02-08 19:50 UTC, raccoonroman commented on css/style.css
> +  margin: 0 auto 16px auto;
```suggestion
  margin: 0 auto 16px;
```

2021-02-08 19:50 UTC, raccoonroman commented on css/style.css
> +  margin: 0 0 25px 0;
```suggestion
  margin: 0 0 25px;
```

2021-02-08 19:50 UTC, raccoonroman commented on css/style.css
> +  text-transform: uppercase;
многие свойсва лишние так как они наследуются от body: font-weight, font-size, text-transform

2021-02-08 19:50 UTC, raccoonroman commented on css/style.css
> +  line-height: 21px;
свойства уже прописаны для body, нет смысла их писать еще раз

2021-02-08 19:50 UTC, raccoonroman commented on css/style.css
> +  height: 36px;
не нужно ограничивать размеры кнопок. Всегда должно быть место для переполнения если вдруг текста будет больше https://up.htmlacademy.ru/htmlcss/30/criteries#d19

2021-02-08 19:50 UTC, raccoonroman commented on css/style.css
> +  color: var(--basic-black);
```suggestion
  color: inherit;
```

2021-02-08 19:50 UTC, raccoonroman commented on css/style.css
> +  line-height: 21px;
Не нужно писать лишних свойств! Не повторяйся https://ru.wikipedia.org/wiki/Don’t_repeat_yourself

2021-02-08 19:50 UTC, raccoonroman commented on css/style.css
> +  height: 27px;
верстка не пройдет тест на переполнение контентом https://up.htmlacademy.ru/htmlcss/30/criteries#d19

2021-02-08 19:50 UTC, raccoonroman commented on css/style.css
> +  height: 27px;
верстка не пройдет тест на переполнение контентом https://up.htmlacademy.ru/htmlcss/30/criteries#d19

2021-02-08 19:50 UTC, raccoonroman commented on css/style.css
> +  width: 110px;
верстка не пройдет тест на переполнение контентом https://up.htmlacademy.ru/htmlcss/30/criteries#d19
Используй паддинги.

2021-02-09 14:06 UTC, timeria commented on css/style.css
> +  url("../fonts/ptsans.woff") format("woff");
У меня в хроме почему-то нет такой ошибки http://prntscr.com/yum0sx И если убрать подключение на самой странице шрифты становятся совсем другие вот так http://prntscr.com/yum8ef Не пойму в чем дело?

2021-02-09 20:30 UTC, raccoonroman requested changes
шрифт PT Sans не подключен к проекту

2021-02-10 21:34 UTC, raccoonroman approved these changes

2021-02-10 21:34 UTC, merged